# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages
sudo: required
before_install:
  - sudo add-apt-repository -y ppa:cran/poppler
  - sudo apt-get update
  - sudo apt-get install -y libpoppler-cpp-dev
